all: clean Solution.class DFAndOffset.class DocTableDetails.class Postings.class

Solution.class:
	javac Solution.java

clean:
	rm -f Solution.class
	rm -f DFAndOffset.class 
	rm -f DocTableDetails.class 
	rm -f Postings.class
